### PR TITLE
Basic Auth with remote nodes or servers

### PR DESCRIPTION
**Pull request by TurnipXenon**
## Overview

Add basic auth (it should theoretically work on all types of auth) for remote node access to current server or host.

## Changes

- Add new field `author_type` in `Author`
- Modify how `is_authenticated` works such that it returns False for inactive or deactivated nodes
- Add custom permissions for specifying whether we want to authenticate only authors or not (in `authors/permissions.py`)
- Add new view `RemoteNodeView` for allowing other groups to test authentication at `/remote-node/`
- Add BasicAuthentication
- Add convenience function 'get_all_authors` and `get_author` which excludes server/node-type Authors

## Questionable design decisions
- Using Author for authenticating remote nodes is an easy thing to do but seems weird that a Node is an Author
- Turning BasicAuthentication on system-wide! If wanted, I could try finding out a way to limit BasicAuthentication only for node/server type Authors. And if I should do that, how much to prioritize.

## Testing

See [remote_node.md](https://github.com/hgshah/cmput404-project/blob/turnip/node-auth/docs/remote_node.md)

Also run:
```bash
python manage.py tests authors
```

## Screenshot
image

### CODE REVIEW

**Comment by amandanguyeen** [comment]
1. So a node is an author except it exists more as a concept than an actual object right? 
2.And what makes an author a node is Author_Type? 
3. When we create a superuser, do we specify the author_type? or is it determined somewhere in your code?
4. Previously when creating a superuser, we specified the host, but I'm guessing with handling remote servers, the host should be handled on the backend right?

**Comment by amandanguyeen** [comment]
> > So a node is an author except it exists more as a concept than an actual object right?
> 
> Yep! I'm just taking advantage of the already built-in authentication stuff that the Author has.
> 
> > And what makes an author a node is Author_Type?
> 
> Yeah
> 
> > When we create a superuser, do we specify the author_type? or is it determined somewhere in your code?
> 
> The default value for author_type is local_author. This works even without setting it to anything. Basically it's an Author by default unless you set that field explicitly.
> 
> > Previously when creating a superuser, we specified the host, but I'm guessing with handling remote servers, the host should be handled on the backend right?
> 
> Hmm... You're correct on this one. We might have to lax the requirement for having a host entry, except when you're a Node-type Author. We'll find out more when we have time to connecting with a different server.

Okay follow up question: what do you mean by node type author? Aren't all authors a node automatically?

**Comment by TurnipXenon** [comment]
> Okay follow up question: what do you mean by node type author? Aren't all authors a node automatically?

Oh, when I meant by note-type author, it meant that their `author_type` field is not `local_author`. Their field is either `active_remote_node` or `inactive_remote_node`. 

That one field is the only distinction between an Author we treat as an Author, and an Author we treat as a Node.

**Comment by amandanguyeen** [comment]
good call on the `/remote-node/` endpoint!

**Pull request merged**
